Repository vaibhavagarwal47/Competitive-Programming-Questions, pull requests merged in 2022-10, with the labels that each got.

#19 codechef_altering_strings.cpp
  CodeChef/codechef_alternating_strings.cpp
Labels: hacktoberfest-accepted, HACKTOBERFEST ACCEPTED

#20 Array Questions
  CodeChef/array.cxx
Labels: hacktoberfest-accepted, HACKTOBERFEST ACCEPTED

#21 Create Longest Increasing Subsequence
  450-Question-Series/Longest Increasing Subsequence
Labels: hacktoberfest-accepted, HACKTOBERFEST ACCEPTED

#22 Create Edit Distance
  450-Question-Series/Edit Distance
Labels: hacktoberfest-accepted, HACKTOBERFEST ACCEPTED

#23 Create Coin Change
  450-Question-Series/Coin Change
Labels: hacktoberfest-accepted, HACKTOBERFEST ACCEPTED

#24 Create Equal Sum Partition
  450-Question-Series/Equal Sum Partition
Labels: hacktoberfest-accepted, HACKTOBERFEST ACCEPTED

#25 Create Rod Cutting
  450-Question-Series/Rod Cutting
Labels: hacktoberfest-accepted, HACKTOBERFEST ACCEPTED

#29 added code of conduct
  CODE_OF_CONDUCT.md
Labels: hacktoberfest-accepted

#28 Add a Leetcode medium level question - Clone Graph in C++
  LeetCode/clone_graph.cpp
Labels: hacktoberfest-accepted, HACKTOBERFEST ACCEPTED

#32 added codechef lunchtime
  CodeChef/LunchTime/September LTIME112/EQUALIZEAB.java
  CodeChef/LunchTime/September LTIME112/FLIPCARDS.java
  CodeChef/LunchTime/September LTIME112/PermutationCreation.java
  CodeChef/LunchTime/September LTIME112/STICKBREAK.java
  CodeChef/LunchTime/September LTIME112/Sleep.java
Labels: hacktoberfest-accepted, HACKTOBERFEST ACCEPTED

#33 Added starters 58 solution
  CodeChef/Starters 58 Division 4 (Rated)/ARRAYBREAK.py
  CodeChef/Starters 58 Division 4 (Rated)/RANKLISTPAGE.py
  CodeChef/Starters 58 Division 4 (Rated)/REACHTARGET.py
Labels: hacktoberfest-accepted, HACKTOBERFEST ACCEPTED

#35 Create hotelprices.cpp
  Hackerrank/hotelprices.cpp
Labels: hacktoberfest-accepted, HACKTOBERFEST ACCEPTED

#36 Create GEOPOS.cpp
  CodeChef/GEOPOS.cpp
Labels: hacktoberfest-accepted

#37 Create sorting_segments.cpp
  CodeChef/sorting_segments.cpp
Labels: documentation, hacktoberfest-accepted, HACKTOBERFEST ACCEPTED

#38 Codechef & Leetcode problems and solution added
  CodeChef/AddToSubsequence.cpp
  LeetCode/TwoSum.cpp
Labels: hacktoberfest-accepted

#39 Codechef Starters 59 solutions added (Div-4)
  CodeChef/Starters 59 Division 4 (Rated)/AUDIBLE.py
  CodeChef/Starters 59 Division 4 (Rated)/HAPPYSTR.py
  CodeChef/Starters 59 Division 4 (Rated)/SPECIALITY.py
  CodeChef/Starters 59 Division 4 (Rated)/SUSSTR.py
Labels: hacktoberfest-accepted

#40 added linked list
  Algorithms/Linked_list/AddingElements.c
  Algorithms/Linked_list/DeletionElement.c
Labels: hacktoberfest-accepted

#41 Added solutions for various codechef, codeforces and leetcode problems.
  CodeChef/August Challenge 2021 Division 3 (Rated)/CHFINVNT.py
  CodeChef/August Challenge 2021 Division 3 (Rated)/OLYRANK.py
  CodeChef/August Challenge 2021 Division 3 (Rated)/PROBDIFF.py
  CodeChef/begineer/FLOW001.py
  CodeChef/begineer/FLOW002.py
  CodeChef/begineer/FLOW006.py
  CodeChef/begineer/INTEST.py
  CodeChef/begineer/MAXTHEMIN.py
  CodeChef/begineer/START01.py
  CodeChef/begineer/TLG.py
  CodeChef/easy/CIELAB.py
  CodeChef/easy/FCTRL.py
  CodeChef/easy/HORSES.py
  CodeChef/easy/JOHNY.py
  CodeChef/easy/TEST.py
  CodeForces/Codeforces Div. 2, A/112A - Petya and Strings.py
  CodeForces/Codeforces Div. 2, A/118A - String Task.py
  CodeForces/Codeforces Div. 2, A/160A - Twins.py
  CodeForces/Codeforces Div. 2, A/4A - Watermelon.py
  CodeForces/Codeforces Div. 2, A/71A - Way Too Long Words.py
  LeetCode/13 Roman to Integer.py
  LeetCode/383. Ransom Note.py
  LeetCode/412. Fizz Buzz.py
Labels: hacktoberfest-accepted

#43 added beginners questions
  CodeChef/begineer/BLACKJACK.py
  CodeChef/begineer/DNASTRAND.py
  CodeChef/begineer/JENGA.py
Labels: hacktoberfest-accepted

#44 Added October Long 2022 questions
  CodeChef/October Long 2022 Division 4 (Rated)/BUILDINGRACE.py
  CodeChef/October Long 2022 Division 4 (Rated)/MINPIZZA.py
  CodeChef/October Long 2022 Division 4 (Rated)/PODIUM.py
  CodeChef/October Long 2022 Division 4 (Rated)/SINGLEOP1.py
  CodeChef/October Long 2022 Division 4 (Rated)/SINGLEOP2.py
Labels: hacktoberfest-accepted

#45 Create Best Time to Buy and Sell Stock.cpp
  LeetCode/Best Time to Buy and Sell Stock.cpp
Labels: hacktoberfest-accepted

#46 Create Contains_Duplicate.cpp
  LeetCode/Contains_Duplicate.cpp
  LeetCode/Richest_Customer_Wealth.cpp
Labels: hacktoberfest-accepted

#48 Added K-smallest program to 450-question-series
  450-Question-Series/k_smallest.cpp
Labels: hacktoberfest-accepted

#50 Longest Palindromic Substring
  LeetCode/longest_palindromic_substring.cpp
Labels: hacktoberfest-accepted

#52 Solution of all_nodes_distance_k_in_binary_tree added in CPP
  LeetCode/all_nodes_distance_K_in_binary_tree.cpp
Labels: hacktoberfest-accepted

#54 Adding 1741D-Masha-and-a-Beautiful-Tree.cpp
  CodeForces/1741D-Masha-and-a-Beautiful-Tree.cpp
Labels: hacktoberfest-accepted

#56 Adding 1068A-Birthday.cpp
  CodeForces/1068A-Birthday.cpp
Labels: hacktoberfest-accepted

#57 adding minimise lcs code from codechef
  CodeChef/Minimise_Lcs.cpp
  CodeChef/Minimise_Lcs.exe
Labels: hacktoberfest-accepted

#60 added longest substring without repeating char in cpp language
  LeetCode/longestSubstrWithoutRepChar.cpp
  LeetCode/searchInRotatedSortedArray.cpp
Labels: hacktoberfest-accepted

#63 Created Increasing.cpp and added question link
  CodeForces/Increasing.cpp
Labels: hacktoberfest-accepted

#65 Create 11.Container_with_most_water.cpp
  LeetCode/11.Container_with_most_water.cpp
Labels: hacktoberfest-accepted

#64 Create Kth Not divisible by N with question link
  CodeForces/KthNotDivisibleByN.cpp
Labels: hacktoberfest-accepted

#67 added Valid Sudoku problem with Python solution
  LeetCode/ValidSudoku.py
Labels: hacktoberfest-accepted

#68 Create inorder_binary_traversal.py
  Algorithms/Searching Algorithms/inorder_binary_traversal.py
Labels: hacktoberfest-accepted

#69 Create products_all_ints.py
  Algorithms/products_all_ints.py
Labels: hacktoberfest-accepted

#70 Count and say problem and solution.
  450-Question-Series/Count and say Pattern.cpp
Labels: hacktoberfest-accepted
